// <auto-generated />
namespace OnlineConsult.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reintroduceIDaskey2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reintroduceIDaskey2));
        
        string IMigrationMetadata.Id
        {
            get { return "201510251724384_re-introduce-ID-as-key2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
