// <auto-generated />
namespace OnlineConsult.MigApp
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testmig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testmig));
        
        string IMigrationMetadata.Id
        {
            get { return "201510251822322_testmig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
