// <auto-generated />
namespace OnlineConsult.MigApp
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_message_param_consult_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_message_param_consult_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201512110115013_add_message_param_consult_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
